### ISSUE TITLE
请教：在群晖上运行应该如何配置？

### ISSUE THREAD

**Issue by lanefengsh** [Mikubill/efb-wechat-docker#10]
你好。我从群晖的Docker中安装了您的代码。如何能配置docker run -d -t --name "efbwechat" -e TOKEN=xxxx -e ADMIN=xxxx mikubill/efbwechat和docker logs -f efbwechat 呢？必须通过SSH的方式来实现吗？

谢谢！

**Comment by Mikubill** [comment]
大概需要一个可以查看二维码的地方...

如果实在没有ssh的话可以考虑先在其他地方部署efbwechat，登陆后再把相关文件挂载到这个docker的容器中

>

**Comment by lanefengsh** [comment]
> 大概需要一个可以查看二维码的地方... 如果实在没有ssh的话可以考虑先在其他地方部署efbwechat，登陆后再把相关文件挂载到这个docker的容器中
> […](#)

感谢回复！
不好意思我没有说明白。
我群晖中运行Docker没有问题，二维码也可以通过Docker的终端机来显示。但是因为我找不到配置的文件，即使登入SSH，也找不到efb的config文件在哪里。
我本来的想法是，把token和admin提前写入config文件，这样看起来开启docker后就自动运行。不知道理解的对不对。再次感谢！
<img width="1126" alt="截屏2020-03-29 17 32 52" src="https://user-images.githubusercontent.com/49373829/77845736-bf58bc80-71e3-11ea-88ac-b0b67ebf17b9.png">

**Comment by Mikubill** [comment]
设置token和admin就会自动在部署容器时将这两个变量写入容器的配置文件中，具体位置在
/opt/app/ehforward_config/profiles/default/blueset.telegram/config.yaml

如果想直接修改/保存配置文件的话可以将该文件mount出来，只需要在docker run的时候使用-v进行挂载即可。

>

**Comment by lanefengsh** [comment]
> 设置token和admin就会自动在部署容器时将这两个变量写入容器的配置文件中，具体位置在 /opt/app/ehforward_config/profiles/default/blueset.telegram/config.yaml 如果想直接修改/保存配置文件的话可以将该文件mount出来，只需要在docker run的时候使用-v进行挂载即可。
> […](#)

感谢您的及时回复。我通过ssh登录一直找不到opt下面的文件。不管是用root还是管理员权限的账号，都显示opt文件夹下只有一个containerd文件夹。不好意思，麻烦您了。

**Comment by Mikubill** [comment]
`/opt/app/ehforward_config/`是容器里的目录啦，需要先`docker exec -ti efbwechat
bash`切换到容器中，然后再进行操作

>

**Comment by lanefengsh** [comment]
> `/opt/app/ehforward_config/`是容器里的目录啦，需要先`docker exec -ti efbwechat bash`切换到容器中，然后再进行操作
> […](#)

十分感谢，这个已经搞定了。
现在通过扫描二维码登录后，出现了错误，docker就关闭了。烦请看一下图片：
<img width="933" alt="截屏2020-03-29 18 42 14" src="https://user-images.githubusercontent.com/49373829/77847117-35155600-71ed-11ea-8eb6-b5282271450b.png">

**Comment by Mikubill** [comment]
尝试（从头）重新构建容器或重新扫码登陆，如果仍出现问题，有可能是账户问题（不允许在线登陆，可以到微信网页版https://wx.qq.com/ 测试一下）
ref: https://github.com/blueset/efb-wechat-slave/issues/25

**Comment by lanefengsh** [comment]
> 尝试（从头）重新构建容器或重新扫码登陆，如果仍出现问题，有可能是账户问题（不允许在线登陆，可以到微信网页版https://wx.qq.com/ 测试一下）
> ref: [blueset/efb-wechat-slave#25](https://github.com/blueset/efb-wechat-slave/issues/25)

十分感谢，的确是微信限制了网页登录的问题。
在这里写一下群晖docker处理的方法，以备其他小伙伴参考：

Docker容器配置好，运行，然后点终端机，在终端中新建-通过命令新建，输入/bin/sh，点击sh
输入 vi /opt/app/ehforward_config/profiles/default/blueset.telegram/config.yaml
编辑config的token和admin，admin后面是否需要加[]，需要测试一下，因为我这里没成功所以不清楚。
重启应该就可以了。
感谢作者的指导。

**Comment by Mikubill** [comment]
Closed.
