### ISSUE TITLE
扫码登录后提示:ValueError: Admin ID is expected to be an int, but {673912xxx: None} is found.

### ISSUE THREAD

**Issue by Loga1n** [Mikubill/efb-wechat-docker#3]
系统Ubuntu 18.04

**Comment by Mikubill** [comment]
1. 输入命令时把大括号去掉，即如下的形式
` -e ADMIN=xxxxxxxxx`

2. 检查Admin ID和Token是否正确。

**Comment by R0ac4** [comment]
> 1. 输入命令时把大括号去掉，即如下的形式
>    ` -e ADMIN=xxxxxxxxx`
> 2. 检查Admin ID和Token是否正确。

token需要删除大括号吗？

**Comment by Mikubill** [comment]
是的。

**Comment by Loga1n** [comment]
已解决 谢谢作者
