### ISSUE TITLE
发送Telegram里的贴纸给微信好友提示错误

### ISSUE THREAD

**Issue by Loga1n** [Mikubill/efb-wechat-docker#4]
Message is not sent.

OSError('cannot identify image file <tempfile._TemporaryFileWrapper object at 0x7f12e50>',)

**Comment by Mikubill** [comment]
已修复。重新使用新的Dockerfile构建或docker pull mikubill/efbwechat即可。
 
(docker pull的话可能要稍等一下，docker hub 好像还没build完
